apiVersion: v1
data:
  relay: |
    receivers:
      k8sobjects:
        objects:
          - name: pods
            mode: pull
          - name: events
            mode: watch
      k8s_cluster:
        collection_interval: 10s
        node_conditions_to_report: [ "Ready", "MemoryPressure", "DiskPressure", "PIDPressure", "NetworkUnavailable" ]
        allocatable_types_to_report: [ "cpu", "memory", "ephemeral-storage", "storage" ]
        distribution: kubernetes
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp/traces:
        endpoint: data-prepper:21890
        tls:
          insecure: true
      otlp/data-prepper:
        endpoint: data-prepper:21891
        tls:
          insecure: true
      otlp/logs:
        endpoint: data-prepper:21892
        tls:
          insecure: true
    service:
      pipelines:
        traces: 
          receivers: [otlp]
          exporters: [otlp/traces]
        metrics:
          receivers: [k8s_cluster]
          exporters: [otlp/data-prepper]
        logs:
          receivers: [k8sobjects]
          exporters: [otlp/logs]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-otel-demo
    meta.helm.sh/release-namespace: otel-collector
  labels:
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/version: 0.105.0
    helm.sh/chart: opentelemetry-collector-0.100.0
  name: otel-collector-cluster-opentelemetry-collector
